package com.spring.common.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TbVersion generated by hbm2java
 */
@Entity
@Table(name = "tb_version", catalog = "mservice_hjtech")
public class TbVersion implements java.io.Serializable {

	private Long tvId;
	private String tvVersion;
	private String tvName;
	private String tvDesp;
	private String tvUrl;
	private Integer tvType;
	private Integer tvStatus;
	private Timestamp tvAddDate;

	public TbVersion() {
	}

	public TbVersion(String tvVersion, String tvName, String tvDesp, String tvUrl, Integer tvType, Integer tvStatus) {
		this.tvVersion = tvVersion;
		this.tvName = tvName;
		this.tvDesp = tvDesp;
		this.tvUrl = tvUrl;
		this.tvType = tvType;
		this.tvStatus = tvStatus;
	}

	public TbVersion(String tvVersion, String tvName, String tvDesp, String tvUrl, Integer tvType, Integer tvStatus,
			Timestamp tvAddDate) {
		this.tvVersion = tvVersion;
		this.tvName = tvName;
		this.tvDesp = tvDesp;
		this.tvUrl = tvUrl;
		this.tvType = tvType;
		this.tvStatus = tvStatus;
		this.tvAddDate = tvAddDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tv_id", unique = true, nullable = false)
	public Long getTvId() {
		return this.tvId;
	}

	public void setTvId(Long tvId) {
		this.tvId = tvId;
	}

	@Column(name = "tv_version", nullable = false, length = 20)
	public String getTvVersion() {
		return this.tvVersion;
	}

	public void setTvVersion(String tvVersion) {
		this.tvVersion = tvVersion;
	}

	@Column(name = "tv_name", nullable = false, length = 10)
	public String getTvName() {
		return this.tvName;
	}

	public void setTvName(String tvName) {
		this.tvName = tvName;
	}

	@Column(name = "tv_desp", nullable = false, length = 500)
	public String getTvDesp() {
		return this.tvDesp;
	}

	public void setTvDesp(String tvDesp) {
		this.tvDesp = tvDesp;
	}

	@Column(name = "tv_url", nullable = false, length = 100)
	public String getTvUrl() {
		return this.tvUrl;
	}

	public void setTvUrl(String tvUrl) {
		this.tvUrl = tvUrl;
	}

	@Column(name = "tv_type", nullable = false)
	public Integer getTvType() {
		return this.tvType;
	}

	public void setTvType(Integer tvType) {
		this.tvType = tvType;
	}

	@Column(name = "tv_status", nullable = false)
	public Integer getTvStatus() {
		return this.tvStatus;
	}

	public void setTvStatus(Integer tvStatus) {
		this.tvStatus = tvStatus;
	}

	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+08:00")
	@Column(name = "tv_add_date", length = 19)
	public Timestamp getTvAddDate() {
		return this.tvAddDate;
	}

	public void setTvAddDate(Timestamp tvAddDate) {
		this.tvAddDate = tvAddDate;
	}

}
